apiVersion: 0.1.0
environments:
  aws-eks-test:
    destination:
      namespace: aws-eks-deep-learning-benchmark
      server: https://localhost
    k8sVersion: v1.12.7
    path: aws-eks-test
  default:
    destination:
      namespace: default
      server: https://localhost
    k8sVersion: v1.12.7
    path: default
kind: ksonnet.io/app
name: workflows
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
