---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    persistevolume: ml-benchmark
  name: benchmark-pv
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /benchmark/
    server: 10.100.89.205

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      persistevolume: ml-benchmark
  storageClassName: ""
