apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: fsx.csi.aws.com
    volumeAttributes:
      dnsname: fs-038707de30ab71bc9.fsx.us-west-2.amazonaws.com
    volumeHandle: fs-038707de30ab71bc9
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fsx-sc
  volumeMode: Filesystem
